Fix cross-version step launch with --mpi=none.
Need to translate NO_VAL <-> MPI_PLUGIN_NONE for older versions,
otherwise step launch will fail with
	error: _send_slurmstepd_init failed
and a stray slurmstepd will be left stuck in mpi_conf_recv_stepd().

Co-authored-by: Danny Auble <da@schedmd.com>