Do not build switch/cray_aries plugin on FreeBSD/NetBSD/macOS.
Wrapping the plugin interface with an #ifdef block as was previously
done still results in the plugin being generated, but without any
of the plugin symbols present. This will then cause errors when
running user commands similar to:
error: Couldn't load specified plugin name for switch/cray_aries: Plugin name/type/version symbol missing

Bug 7017.