Fix recovering reservations that requested HRES
Any reservation that reserved HRES was purged when slurmctld was restarted
or reconfigured because HRES were not yet initialized. For example, the
following slurmctld log messages show the reservation requested 400 of the
HRES "natural" but zero are configured:

Recovered state of reservation hresresv
debug:  Licenses count requested higher than configured (natural: 400 > 0)
licenses: request_license=natural lic_id=65534 total=400 used=0
error: Reservation hresresv has invalid licenses (natural:400)
error: Purging invalid reservation record hresresv

Fix this by calling hres_init() before loading reservations from state.

Changelog: Avoid purging reservations that reserved HRES when restarting
 or reconfiguring slurmctld.
Issue: 50445
Cherry-picked: aaf7d48696