Fix regression in 21.08.0 that broke dynamic future nodes
Broken by commit 4cca854e31 (bug 11621).

When a FUTURE node slurmd initializes, the following information appears
in the slurmd log:

error: _find_node_record: lookup failure for node "node01"
error: slurmd initialization failed

With FUTURE nodes, the hostname for that node is not known by the
controller until the node registers.

Bug 12959

Signed-off-by: Marshall Garey <marshall@schedmd.com>