Fix loading non-default QOS on pending jobs from pre-24.11 state
If a job was submitted to a specific QOS, and not the default QOS, this
would be lost on upgrade to 24.11 and could be seen with messages like:

  error: This association 7(account='', user='', partition='') does not have access to qos normal
  job_mgr_load_job_state: JobId=<job-id> ineligible due to invalid qos

Changelog: Fix loading non-default QOS on pending jobs from pre-24.11
 state.
Ticket: 21812