slurmd - Always respond to REQUEST_ACCT_GATHER_ENERGY
If there are no sensors, then slurmd did not respond to the RPC, and the
following errors would appear in the slurmd log file and in the user's step:

error: _get_joules_task: can't get info from slurmd
error: slurm_get_node_energy: Zero Bytes were transmitted or received

The "Zero Bytes were transmitted or received" error happens because slurmd
did not respond to slurmstepd's REQUEST_ACCT_GATHER_ENERGY RPC.

Even if the plugin does not find any sensors, always respond to this RPC. In
the case that there are no sensors, the response will be zero'd data. This
avoids the errors showing up in slurmd and the user's step:

Ticket 19369

Signed-off-by: Michael Norris <michael.norris@schedmd.com>