Fix layouts code to only allow setting a boolean.
Before it would allow all sorts of things like
adding/subtracting/multiplying/etc.  It would cause warnings such as

/home/bart/slurm-tmp5/src/common/layouts_mgr.c: In function ‘_layouts_load_automerge’:
/home/bart/slurm-tmp5/src/common/layouts_mgr.c:363:21: error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]
   *lvalue = *lvalue * *rvalue;     \
             ~~~~~~~~^~~~
/home/bart/slurm-tmp5/src/common/layouts_mgr.c:1034:4: note: in expansion of macro ‘_entity_update_kv_helper’
    _entity_update_kv_helper(type_t, operator); \
    ^~~~~~~~~~~~~~~~~~~~~~~~
/home/bart/slurm-tmp5/src/common/layouts_mgr.c:1086:4: note: in expansion of macro ‘_layouts_load_merge’
    _layouts_load_merge(bool, s_p_get_boolean);
[tag] [reply] [−]￼ Private Comment 16

Bug 4062