Fix cons_res GRES overallocation for --gres-flags=disable-binding.
Commit aa61233bb27 effectively disabled gres_plugin_job_test in cons_res for
GRES_DISABLE_BIND requests. This resulted in job allocations without the
requested gres, leading to errors like:

error: gres/gpu: job <X> node <Y> overallocated resources by 8, (16 > 8)

Bug 7580.