Fix GRES config parsing logic in slurmd
Slurmd was generating errors of this sort for all GRES:
error: Ignoring gres.conf record, invalid name: mps
This was due to some GRES setup logic not being invoked
on the slurmd. In any case, the relevant checking now only
happens on the slurmctld.