Fix xassert on calling priority plugin before being loaded
I ran into this while restarting the controller after reducing a node's
gres from 4 to 2 and that had a job running using the 4 gpus.

e.g.
_validate_node_gres_cnt: Killing job 349143: gres/gpu count mismatch on node lappy9 (4 != 2)
error: Aborting JobId=349143 due to use of invalid GRES configuration

5  0x00007ffff7e2f11e in __xassert_failed (expr=0x7ffff7ed3f7d "g_priority_context", file=0x7ffff7ed3ee0 "../../../../slurm/src/interfaces/priority.c", line=173, func=0x7ffff7ed4050 <__func__.0> "priority_g_
ob_end") at ../../../../slurm/src/common/xassert.c:57
6  0x00007ffff7e83d04 in priority_g_job_end (job_ptr=0x5555557e69c0) at ../../../../slurm/src/interfaces/priority.c:173
7  0x000055555557531a in _adjust_limit_usage (type=3, job_ptr=0x5555557e69c0) at ../../../../slurm/src/slurmctld/acct_policy.c:807
8  0x000055555557a57e in acct_policy_job_fini (job_ptr=0x5555557e69c0) at ../../../../slurm/src/slurmctld/acct_policy.c:2675
9  0x000055555562cb5a in deallocate_nodes (job_ptr=0x5555557e69c0, timeout=false, suspended=false, preempted=false) at ../../../../slurm/src/slurmctld/node_scheduler.c:314
10 0x00005555556677ea in _sync_nodes_to_comp_job () at ../../../../slurm/src/slurmctld/read_config.c:3196
11 0x0000555555663fb2 in read_slurm_conf (recover=1, reconfig=false) at ../../../../slurm/src/slurmctld/read_config.c:1873
12 0x000055555558d415 in main (argc=2, argv=0x7fffffffd9b8) at ../../../../slurm/src/slurmctld/controller.c:716

This is due to changes to not lazily load plugins (for the better).

Bug 14557

Signed-off-by: Danny Auble <da@schedmd.com>