Tag alias for fatal() and fatal_abort() with noreturn as well.
Otherwise GCC 9.1 complains with:
../../../../slurm/src/common/log.c:113:27: error: 'slurm_fatal_abort'
specifies less restrictive attribute than its target 'fatal_abort':
'noreturn' [-Werror=missing-attributes]