Fix scrun fatal()'ing
The following is an example of the failure with podman hooked up to use
scrun:

$ podman run alpine uptime
Error: OCI runtime error: slurm: scrun: lua: initialized scrun.lua
scrun: fatal: _try_start: start request queue empty
scrun: fatal: _wait_create_pid: anchor 3732817 killed by signal 6

The anchor creates a pipe to coordinate startup of the child - the parent
waits for the child to send it data (its PID, but it doesn't matter) over
the pipe to indicate that it has started up successfully. Then the parent
exits. That is the purpose of the pipe.

Starting in commit d8e3da4fc6, con_set_polling() optimistically sets the
connection flag FLAG_CAN_READ. This makes conmgr try to read from the fd.

This exposed a latent bug in scrun in _anchor_child(), where the same end of
a pipe was set as both an input and output fd. Each end of the pipe is
unidirectional. This end of the pipe is not readable; it is only writeable.
Prior to commit d8e3da4fc6, this bug was not exposed because conmgr
previously never tried to read from this fd.

When _handle_connection() calls read_input() and it reads the fd, read()
returns -1 with errno == EBADF and conmgr closes the connection.

When the connection is closing, conmgr calls the on_finish() callback which
is set to _on_startup_con_fin(). This calls _try_start(). _try_start()
fatal()'s because it meets the following if condition:

    if (state.status < CONTAINER_ST_CREATED) {

The path to get here is much faster than the path that sets state.status to
CONTAINER_ST_CREATED, which is the following:

_anchor_child() queues get_allocation() which sets the state.step_id (the
job id) and queues check_allocation(). This calls slurm_job_node_ready(). If
that returns SLURM_SUCCESS, it queues on_allocation(). on_allocation() sets
the container status to CONTAINER_ST_CREATED.

Because on_allocation() hasn't happened yet, _try_start() fatal()'s.

Fixing this requires two things:

(1) Do not set input_fd - pass -1 instead. This ensures that conmgr will no
longer try to read it. However, having an input_fd kept _handle_connection()
from exiting. With input_fd set to -1 and without any queued work or
writes, _handle_connection() will close the connection. This will still
result in calling the on_finish() callback before on_allocation(), resulting
in the same fatal().

(2) To make sure conmgr does not close the connection too early, set the
connection with the quiesce flag. Unquiesce the connection after we have
queued the write in on_allocation(). This ensures that the connection will
not be closed until after the write is done.

Changelog: Fix regression in 26.05.0 that caused scrun to exit with a fatal
 error before starting the container.
Ticket: 25279