Modify the configure m4 macro for rrdtool to work better
such that  1) specifying --without-rrdtool or --with-rrdtool=no works as
expected, disabling rrdtool build and  2) the link test also tests for
rrd_info_t which was not present in the old rrdtool-devel-1.2.27 which I
happen to have installed. It is present in the newer rrdtool I used from
rpmforge for centos5 rrdtool-devel-1.4.7-1.el5.rf.x86_64.
rrd_info_t was chosen because it was in the output of make when it failed.

That is I saw this error:
/bin/sh ../../../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../slurm -I../../../.. -I../../../../src/common  -I/usr/include    -DNUMA_VERSION1_COMPATIBILITY -g -O2 -pthread -fno-gcse -MT ext_sensors_rrd.lo -MD -MP -MF .deps/ext_sensors_rrd.Tpo -c -o ext_sensors_rrd.lo ext_sensors_rrd.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../slurm -I../../../.. -I../../../../src/common -I/usr/include -DNUMA_VERSION1_COMPATIBILITY -g -O2 -pthread -fno-gcse -MT ext_sensors_rrd.lo -MD -MP -MF .deps/ext_sensors_rrd.Tpo -c ext_sensors_rrd.c  -fPIC -DPIC -o .libs/ext_sensors_rrd.o
ext_sensors_rrd.c: In function '_rrd_get_last_one':
ext_sensors_rrd.c:198: error: 'rrd_info_t' undeclared (first use in this function)
ext_sensors_rrd.c:198: error: (Each undeclared identifier is reported only once
ext_sensors_rrd.c:198: error: for each function it appears in.)
ext_sensors_rrd.c:198: error: 'data' undeclared (first use in this function)
ext_sensors_rrd.c:198: error: 'data_p' undeclared (first use in this function)