Fix clang build error introduced by commit d977b988242
src/plugins/select/cons_tres/job_test.c:2437:19: error:
equality comparison with extraneous parentheses
[-Werror,-Wparentheses-equality]

	if ((block_inx == -1)) {