Fix missing unlock in group cache code
Going through this code path caused slurmctld to freeze. A way to know
you've hit this patch is by finding this log message in slurmctld log:

error: failed to init group cache entry for uid=

Bug 17984