Correct index in log message
The wrong variable was being used in gres.c to print a message of
this sort:
error: gres/gpu: job 7135 dealloc node ### type ### gres count underflow (# #)
The first number in the parenthesis was based upon the wrong index and it's
contents garbage